### ISSUE TITLE
semPower.powerLav results differences

### ISSUE THREAD

**Issue by mcfanda** [moshagen/semPower#27]
Hi, 
I am using version 2.1.0, R version 4.1.2, and I see a discrepancy in the results obtained with `semPower.powerLav()` depending on which argument is used to set the model. 
The general setup is a simple mediation like the following:
```
med<-semPower.powerMediation('a-priori',bYX=.2,bYM=.4,bMX=.3,nIndicator = c(1, 1, 1),   loadM = c(1, 1, 1), alpha=.05, power=.9,standardized=F)
med$Sigma
     x1    x2     x3
x1 1.00 0.300 0.3200
x2 0.30 1.090 0.4960
x3 0.32 0.496 1.2624
```
Here I get required N=124
Now, if I want to reproduce the results (a part from the expected N which may use different test) I can use:

```
model.H1 <- '
m~  a*x
y~  b*m + c*x
ind:=a*b
'
model.H0 <- '
m~ a*x
y~ b*m + c*x
ind:=a*b
ind == 0
'

Beta <- matrix(c(
  #   X    M    Y
  c(.00, .00, .00),    # X
  c(.30, .00, .00),    # M
  c(.2, .40, .00)     # Y
), nrow=3,ncol=3, byrow=T)

sigma <- semPower.genSigma(Beta = Beta, nIndicator = c(1, 1, 1),     loadM = c(1, 1, 1))[["Sigma"]]

colnames(sigma)<-rownames(sigma)<-c("x","m","y")

res1<-semPower.powerLav(type="a-priori",modelH1=model.H1,modelH0=model.H0,alpha=.05,power=.90,Sigma=sigma, fitH1model = F)
res1$Sigma
     x     m      y
x 1.00 0.300 0.3200
m 0.30 1.090 0.4960
y 0.32 0.496 1.2624
```
The sigma is equal to the one obtained with `semPower.powerMediation()` (N is a bit more N=158, but that's probably the testing strategy, not an issue). 

Now, if I  use modelPop, I get very different results as expected N
 
```
model.pop <- '
m~ .3*x
y~ .4*m + .2*x
'

res2<-semPower.powerLav(type="apriori", modelH1=model.H1, modelH0=model.H0, alpha=.05, power=.90, modelPop=model.pop, fitH1model = F)

res2$sigma
      m    x      y
m 1.090 0.30 0.4960
x 0.300 1.00 0.3200
y 0.496 0.32 1.2624
```
The sigma is not ordered as expected, but the covariances are the same. However, the required N=72 is very different as compared with the one obtained with the Beta matrix. F0 , RMSEA and Mc are all different, only the sigmahat matrices are the same. 
Is this result expected?

**Comment by moshagen** [comment]
Thank you for the report! All three approaches should lead to the same result. There are two unrelated issues at play here. 

First, I was under the impression that defining dummy latents with a single indicator and a fixed loading of 1 (e.g., fx ~ 1*x; fy ~ 1*y; fy ~ fx) is generally equivalent to the simple use of observed variables (y ~ x). As your first two examples illustrate, it turns out that this is not the case when there are non-linear constraints as in a*b==0. The deeper issue is that lavaan currently does not support optimizers that better cope with non-linear constraints (e.g. NPSOL), so a proper solution would be to rely on OpenMx for the mediation models. See https://doi.org/10.1037/met0000259 for a discussion. For now, I added an ugly workaround.

Second, as you suspected, there was also an ordering issue occurring under rather special conditions with a user-provided Sigma.

Now all three approaches give the same result, as it should be.

**Comment by moshagen** [comment]
...now also on CRAN

**Comment by mcfanda** [comment]
great! thank you very much
